#!/usr/bin/env python3
"""Generate an Apifox/OpenAPI document for the static Raw API."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "sources.json"
OUTPUT = ROOT / "docs" / "openapi.json"


JsonObject = dict[str, Any]


def load_json(path: Path) -> JsonObject:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, payload: JsonObject) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def clean_operation_id(*parts: str) -> str:
    text = "_".join(parts)
    text = re.sub(r"[^0-9A-Za-z_]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text or "get_resource"


def response(schema_ref: str, description: str = "OK") -> JsonObject:
    return {
        "description": description,
        "content": {
            "application/json": {
                "schema": {
                    "$ref": schema_ref,
                }
            }
        },
    }


def get_operation(summary: str, description: str, tag: str, operation_id: str, schema_ref: str) -> JsonObject:
    return {
        "tags": [tag],
        "summary": summary,
        "description": description,
        "operationId": operation_id,
        "responses": {
            "200": response(schema_ref),
        },
    }


def add_single(paths: JsonObject, resource: JsonObject) -> None:
    raw_path = "/" + resource["output"].lstrip("/")
    paths[raw_path] = {
        "get": get_operation(
            summary=resource["name"],
            description=f"{resource.get('description', '')}\n\nUpstream path: `{resource['path']}`.",
            tag="Single resources",
            operation_id=clean_operation_id("get", resource["name"]),
            schema_ref="#/components/schemas/KivoEnvelope",
        )
    }


def add_collection(paths: JsonObject, resource: JsonObject) -> None:
    output_dir = resource.get("output_dir", resource["name"]).strip("/")
    index_path = f"/{output_dir}/index.json"
    pages_path = f"/{output_dir}/pages/{{page}}.json"

    paths[index_path] = {
        "get": get_operation(
            summary=f"{resource['name']} index",
            description=(
                f"{resource.get('description', '')}\n\n"
                f"Aggregated collection index generated by StuArchive. "
                f"Upstream path: `{resource['path']}`. List field: `{resource['list_key']}`."
            ),
            tag="Collection indexes",
            operation_id=clean_operation_id("get", resource["name"], "index"),
            schema_ref="#/components/schemas/CollectionIndex",
        )
    }

    page_operation = get_operation(
        summary=f"{resource['name']} page",
        description=(
            f"Original Kivo paginated response mirrored by StuArchive. "
            f"Page numbers start at 1. Upstream path: `{resource['path']}`."
        ),
        tag="Original pages",
        operation_id=clean_operation_id("get", resource["name"], "page"),
        schema_ref="#/components/schemas/KivoEnvelope",
    )
    page_operation["parameters"] = [{"$ref": "#/components/parameters/Page"}]
    paths[pages_path] = {"get": page_operation}

    if resource.get("detail_path"):
        detail_path = f"/{output_dir}/{{id}}.json"
        detail_operation = get_operation(
            summary=f"{resource['name']} detail",
            description=(
                f"Per-id detail response. This file exists only after syncing with "
                f"`python3 scripts/sync.py --include-details`. Upstream template: `{resource['detail_path']}`."
            ),
            tag="Details",
            operation_id=clean_operation_id("get", resource["name"], "detail"),
            schema_ref="#/components/schemas/KivoEnvelope",
        )
        detail_operation["parameters"] = [{"$ref": "#/components/parameters/Id"}]
        paths[detail_path] = {"get": detail_operation}


def build_spec(config: JsonObject) -> JsonObject:
    paths: JsonObject = {
        "/index.json": {
            "get": get_operation(
                summary="API manifest",
                description="StuArchive generated entrypoint listing all resources and Raw URLs.",
                tag="Manifest",
                operation_id="get_manifest",
                schema_ref="#/components/schemas/Manifest",
            )
        }
    }

    for resource in config.get("resources", []):
        if resource.get("mode") == "paginated":
            add_collection(paths, resource)
        else:
            add_single(paths, resource)

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "StuArchive Raw API",
            "version": "1.0.0",
            "description": (
                "Static JSON mirror of public Blue Archive data exposed by Kivo Wiki. "
                "This OpenAPI document is intended for Apifox or other OpenAPI-compatible tools."
            ),
            "license": {
                "name": config.get("license", {}).get("repository", "CC BY-SA 4.0"),
                "url": config.get("license", {}).get("repository_url", "https://creativecommons.org/licenses/by-sa/4.0/"),
            },
        },
        "servers": [
            {
                "url": config["raw_base_url"].rstrip("/"),
                "description": "GitHub Raw data base URL",
            }
        ],
        "externalDocs": {
            "description": "StuArchive API documentation",
            "url": "https://github.com/QuetzalSidera/StuArchive/blob/main/docs/API.md",
        },
        "tags": [
            {"name": "Manifest", "description": "Top-level generated API manifest."},
            {"name": "Single resources", "description": "Kivo single JSON responses mirrored as static files."},
            {"name": "Collection indexes", "description": "Aggregated collection indexes generated by StuArchive."},
            {"name": "Original pages", "description": "Original paginated Kivo API responses."},
            {"name": "Details", "description": "Per-id detail files generated when detail sync is enabled."},
        ],
        "paths": paths,
        "components": {
            "parameters": {
                "Page": {
                    "name": "page",
                    "in": "path",
                    "required": True,
                    "schema": {"type": "integer", "minimum": 1},
                    "description": "Mirrored page number.",
                },
                "Id": {
                    "name": "id",
                    "in": "path",
                    "required": True,
                    "schema": {"type": "string"},
                    "description": "Kivo resource ID.",
                },
            },
            "schemas": {
                "AnyJson": {
                    "description": "Arbitrary JSON object.",
                    "type": "object",
                    "additionalProperties": True,
                },
                "KivoEnvelope": {
                    "type": "object",
                    "additionalProperties": True,
                    "properties": {
                        "code": {"type": "integer"},
                        "codename": {"type": "string"},
                        "data": {"description": "Kivo response payload."},
                        "message": {"type": "string"},
                        "success": {"type": "boolean"},
                        "time": {"type": "integer"},
                        "version": {"type": "string"},
                    },
                    "required": ["code", "message", "success"],
                },
                "Manifest": {
                    "type": "object",
                    "additionalProperties": True,
                    "properties": {
                        "schema_version": {"type": "string"},
                        "name": {"type": "string"},
                        "generated_at": {"type": "string", "format": "date-time"},
                        "source": {"$ref": "#/components/schemas/AnyJson"},
                        "license": {"$ref": "#/components/schemas/AnyJson"},
                        "raw": {"$ref": "#/components/schemas/AnyJson"},
                        "resources": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/AnyJson"},
                        },
                    },
                },
                "CollectionIndex": {
                    "type": "object",
                    "additionalProperties": True,
                    "properties": {
                        "schema_version": {"type": "string"},
                        "name": {"type": "string"},
                        "description": {"type": "string"},
                        "generated_at": {"type": "string", "format": "date-time"},
                        "list_key": {"type": "string"},
                        "id_key": {"type": "string"},
                        "max_page": {"type": "integer"},
                        "synced_pages": {"type": "integer"},
                        "total_items": {"type": "integer"},
                        "details_synced": {"type": "integer"},
                        "items": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/AnyJson"},
                        },
                        "pages": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/AnyJson"},
                        },
                        "details": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/AnyJson"},
                        },
                    },
                },
            },
        },
    }


def main() -> int:
    config = load_json(SOURCES)
    write_json(OUTPUT, build_spec(config))
    print(f"[openapi] wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
